Implemented a method to change the data of packet.
jgromes/LoRaLib pull request #9
Opened 2018-06-11 23:45 UTC by renatocarusos

This method work with char[], string, int or float variables. In float, there have an option to determine how many decimal will be, instead as three, as default.
There is an example sketch too.

2018-06-15 05:59 UTC, jgromes requested changes
Nice, I was thinking of implementing something similar myself, just never got around to actually doing it. Before I merge this, there's a few minor issues, I would be glad if you could address them.

I would like to also rewrite the example code, but I will do that myself after the merge (so that the writing style is consistent across all the examples).

Thanks!

2018-06-15 05:59 UTC, jgromes commented on src/Packet.cpp
> +  this->setPacketData(charArray);
Unneccessary `this` pointer (it is implied when calling member method `setPacketData` from inside its own class).
The same goes for all `this` pointers in this file.

2018-06-15 05:59 UTC, jgromes commented on src/Packet.cpp
> +void Packet::setPacketData(float f, uint8_t decimals) {
This is not a good way to overload functions - you have basically the same code twice here in both implementations of `setPacketData`.

Delete the previous `setPacketData` (line 164) and in this one, add default value to the `decimals` argument in Packet.h

2018-06-15 05:59 UTC, jgromes commented on src/Packet.h
> +    void setPacketData(float f, uint8_t decimals);
Change to `void setPacketData(float f, uint8_t decimals = 3);`

2018-06-15 05:59 UTC, jgromes commented on src/Packet.cpp
> +void Packet::setPacketData(String wordy){
Change the argument to `String str`.

2018-06-16 18:10 UTC, renatocarusos commented
I was really worried about the style of the sample code. But I figured you'd stylize it according to your sketch.

2018-06-16 18:49 UTC, jgromes approved these changes

2018-06-16 18:50 UTC, merged